### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ManavMalhotra** [Quiec/WhatsAsena#18]
My bot crash when I use .img

**Comment by Quiec** [comment]
Can you send log?

**Comment by justinthoms** [comment]
same problem to me some issue are there img....

**Comment by Quiec** [comment]
> same problem to me some issue are there img.... issues fix soon

i need logs

**Comment by ManavMalhotra** [comment]
> > same problem to me some issue are there img.... issues fix soon
> 
> i need logs

I send it on your group but I am not getting replies

**Comment by ManavMalhotra** [comment]
I also having problem using Lydia

**Comment by ManavMalhotra** [comment]
> Can you send log?

![image](https://user-images.githubusercontent.com/64147782/101282441-36c2ff00-37fb-11eb-9736-95fd4b6eece8.png)
