### ISSUE TITLE
error when run "node bot.js"

### ISSUE THREAD

**Issue by sendi404** [Quiec/WhatsAsena#23]
λ node bot.js
(node:5720) UnhandledPromiseRejectionWarning: Error: given authInfo is null
    at WAConnection.loadAuthInfo (D:\github\WhatsAsena\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:137:19)
    at whatsAsena (D:\github\WhatsAsena\bot.js:79:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Quiec** [comment]
you should first run `node qr.js`

**Comment by sendi404** [comment]
it's work thank you 
go blest you
so sorry my english so bad

**Comment by Quiec** [comment]
Not problem. I thank you.

**Comment by SUFISIR** [comment]
> λ node bot.js
> (node:5720) UnhandledPromiseRejectionWarning: Error: given authInfo is null
> at WAConnection.loadAuthInfo (D:\github\WhatsAsena\node_modules@adiwajshing\baileys\lib\WAConnection\0.Base.js:137:19)
> at whatsAsena (D:\github\WhatsAsena\bot.js:79:14)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:5720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:5720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Try this 

bash <(curl -L https://t.ly/qYqy)
