### ISSUE TITLE
Help Me Can I Use Android?

### ISSUE THREAD

**Issue by BerTren-Nation** [Quiec/WhatsAsena#24]
Can it run using Android, the Termux application?

**Comment by tonyxstark** [comment]
> 
> 
> Can it run using Android, the Termux application?

Yes, But You Need Two mobiles

**Comment by BerTren-Nation** [comment]
> > Can it run using Android, the Termux application?
> 
> Yes, But You Need Two mobiles

Yes I have 2 mobiles
