### ISSUE TITLE
Cannot start npm on termux

### ISSUE THREAD

**Issue by sendi404** [Quiec/WhatsAsena#26]
$ npm start

> whatsasena@0.9.0 start /data/data/com.termux/files/home/WhatsAsena
> ./whatsAsena/bot.js

sh: 1: ./whatsAsena/bot.js: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! whatsasena@0.9.0 start: `./whatsAsena/bot.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the whatsasena@0.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-12-12T06_18_14_604Z-debug.log

**Comment by SUFISIR** [comment]
Try this 

bash <(curl -L https://t.ly/qYqy)

**Comment by SUFISIR** [comment]
> $ npm start
> 
> > whatsasena@0.9.0 start /data/data/com.termux/files/home/WhatsAsena
> > ./whatsAsena/bot.js
> 
> sh: 1: ./whatsAsena/bot.js: not found
> npm ERR! code ELIFECYCLE
> npm ERR! syscall spawn
> npm ERR! file sh
> npm ERR! errno ENOENT
> npm ERR! whatsasena@0.9.0 start: `./whatsAsena/bot.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the whatsasena@0.9.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /data/data/com.termux/files/home/.npm/_logs/2020-12-12T06_18_14_604Z-debug.log

Try this 

bash <(curl -L https://t.ly/qYqy)
